# Generated by Django 3.2.5 on 2021-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesteUsuario', '0002_remove_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
